# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe06e1cca8227a6258c9c725b26a44401493f8c41b2ec171bd6c9116b7d96e8d9c5c1574d1e1df92b13133be2d6067772c43336f9880906c3d88a3941be7f5e0
  CLIENT_ID: ******ENTER YOUR INSTAGRAM API CREDENTIALS HERE********
  CLIENT_SECRET: ******ENTER YOUR INSTAGRAM API CREDENTIALS HERE********
  ACCESS_TOKEN: ******ENTER YOUR INSTAGRAM API CREDENTIALS HERE********
  
test:
  secret_key_base: 961843b4da62f4fa59883d9b53456d1bfb46d65be6d8872379b971a26e2f2011d94f39f2beeb755165c39267c46f0407c851e665340dc0792457a99a41e1dd95
  CLIENT_ID: ******ENTER YOUR INSTAGRAM API CREDENTIALS HERE********
  CLIENT_SECRET: ******ENTER YOUR INSTAGRAM API CREDENTIALS HERE********
  ACCESS_TOKEN: ******ENTER YOUR INSTAGRAM API CREDENTIALS HERE********
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  CLIENT_ID: <%= ENV["CLIENT_ID"] %>
  CLIENT_SECRET: <%= ENV["CLIENT_SECRET"] %>
  ACCESS_TOKEN: <%= ENV["ACCESS_TOKEN"] %>